title: CentOS-altarch
content: |
  ARM架构下的CentOS镜像。

  #### Official

  - [https://www.centos.org/download/](https://www.centos.org/download/)

  #### Mirrors

  - [Aliyun](https://developer.aliyun.com/mirror/centos-altarch)
    - [https://developer.aliyun.com/mirror/centos-altarch](https://developer.aliyun.com/mirror/centos-altarch)
  - Tencent
    - [https://mirrors.cloud.tencent.com/centos-altarch/](https://mirrors.cloud.tencent.com/centos-altarch/)
  - HUAWEI
    - [https://repo.huaweicloud.com/centos-altarch/](https://repo.huaweicloud.com/centos-altarch/)
  - 清华
    - [https://mirrors.tuna.tsinghua.edu.cn/centos-altarch/](https://mirrors.tuna.tsinghua.edu.cn/centos-altarch/)
  - 中科大
    - [https://mirrors.ustc.edu.cn/centos-altarch/](https://mirrors.ustc.edu.cn/centos-altarch/)
  - 兰州大学
    - [https://mirror.lzu.edu.cn/centos-altarch/](https://mirror.lzu.edu.cn/centos-altarch/)
  - 北京外国语大学
    - [https://mirrors.bfsu.edu.cn/centos-altarch/](https://mirrors.bfsu.edu.cn/centos-altarch/)