title: Ubunutu
content: |
  #### Official

  - 官方镜像：[https://ubuntu.com/download](https://ubuntu.com/download)

  #### Mirrors

  - [Aliyun](https://developer.aliyun.com/mirror/ubuntu)
    - [https://mirrors.aliyun.com/ubuntu/](https://mirrors.aliyun.com/ubuntu/)
  - Tencent
    - [https://mirrors.cloud.tencent.com/ubuntu/](https://mirrors.cloud.tencent.com/ubuntu/)
  - HUAWEI
    - [https://repo.huaweicloud.com/ubuntu/](https://repo.huaweicloud.com/ubuntu/)
  - 163
    - [http://mirrors.163.com/ubuntu/](http://mirrors.163.com/ubuntu/)
  - Souhu
    - [http://mirrors.sohu.com/ubuntu/](http://mirrors.sohu.com/ubuntu/)
  - 北大
    - [https://mirrors.pku.edu.cn/ubuntu/](https://mirrors.pku.edu.cn/ubuntu/)
  - 清华
    - [https://mirrors.tuna.tsinghua.edu.cn/ubuntu/](https://mirrors.tuna.tsinghua.edu.cn/ubuntu/)
  - 中科大
    - [https://mirrors.ustc.edu.cn/ubuntu/](https://mirrors.ustc.edu.cn/ubuntu/)
  - 浙江大学
    - [http://mirrors.zju.edu.cn/ubuntu/](http://mirrors.zju.edu.cn/ubuntu/)
  - 兰州大学
    - [https://mirror.lzu.edu.cn/ubuntu/](https://mirror.lzu.edu.cn/ubuntu/)
  - 大连东软
    - [http://mirrors.neusoft.edu.cn/ubuntu/](http://mirrors.neusoft.edu.cn/ubuntu/)
  - 上海交通
    - [http://ftp.sjtu.edu.cn/ubuntu/](http://ftp.sjtu.edu.cn/ubuntu/)
  - 北京交通
    - [https://mirror.bjtu.edu.cn/ubuntu/](https://mirror.bjtu.edu.cn/ubuntu/)
  - 大连理工
    - [http://mirror.dlut.edu.cn/ubuntu/](http://mirror.dlut.edu.cn/ubuntu/)
  - 首都在线
    - [http://mirrors.yun-idc.com/ubuntu/](http://mirrors.yun-idc.com/ubuntu/)
  - 南京邮电
    - [http://mirrors.njupt.edu.cn/ubuntu/](http://mirrors.njupt.edu.cn/ubuntu/)
  - 南阳理工
    - [https://mirror.nyist.edu.cn/ubuntu/](https://mirror.nyist.edu.cn/ubuntu/)
  - 重庆大学
    - [https://mirrors.cqu.edu.cn/ubuntu/](https://mirrors.cqu.edu.cn/ubuntu/)
  - 北京外国语大学
    - [https://mirrors.bfsu.edu.cn/ubuntu/](https://mirrors.bfsu.edu.cn/ubuntu/)
  - 哈尔滨工业大学
    - [https://mirrors.hit.edu.cn/ubuntu](https://mirrors.hit.edu.cn/ubuntu)
