title: Deepin
content: |
  #### Official

  - 官方镜像：[https://www.deepin.org/zh/download/](https://www.deepin.org/zh/download/)

  #### Mirrors

  - [Aliyun](https://developer.aliyun.com/mirror/deepin)
    - [https://mirrors.aliyun.com/deepin/](https://mirrors.aliyun.com/deepin/)
  - HUAWEI
    - [https://repo.huaweicloud.com/deepin/](https://repo.huaweicloud.com/deepin/)
  - 163
    - [http://mirrors.163.com/deepin/](http://mirrors.163.com/deepin/)
  - Souhu
    - [http://mirrors.sohu.com/deepin/](http://mirrors.sohu.com/deepin/)
  - 清华
    - [https://mirrors.tuna.tsinghua.edu.cn/deepin/](https://mirrors.tuna.tsinghua.edu.cn/deepin/)
  - 中科大
    - [https://mirrors.ustc.edu.cn/deepin/](https://mirrors.ustc.edu.cn/deepin/)
  - 浙江大学
    - [http://mirrors.zju.edu.cn/deepin/](http://mirrors.zju.edu.cn/deepin/)
  - 兰州大学
    - [https://mirror.lzu.edu.cn/deepin/](https://mirror.lzu.edu.cn/deepin/)
  - 上海交通
    - [http://ftp.sjtu.edu.cn/deepin/](http://ftp.sjtu.edu.cn/deepin/)
  - 南京邮电
    - [http://mirrors.njupt.edu.cn/deepin/](http://mirrors.njupt.edu.cn/deepin/)
  - 南阳理工
    - [https://mirror.nyist.edu.cn/deepin/](https://mirror.nyist.edu.cn/deepin/)
  - 重庆大学
    - [https://mirrors.cqu.edu.cn/deepin/](https://mirrors.cqu.edu.cn/deepin/)
  - 北京外国语大学
    - [https://mirrors.bfsu.edu.cn/deepin/](https://mirrors.bfsu.edu.cn/deepin/)
  - 哈尔滨工业大学
    - [https://mirrors.hit.edu.cn/deepin/](https://mirrors.hit.edu.cn/deepin/)