title: Fedora
content: |
  #### Official

  - 官方镜像：[https://getfedora.org/en/server/download/](https://getfedora.org/en/server/download/)

  #### Mirrors

  - [Aliyun](https://developer.aliyun.com/mirror/fedora)
    - [https://mirrors.aliyun.com/fedora/](https://mirrors.aliyun.com/fedora/)
  - Tencent
    - [https://mirrors.cloud.tencent.com/fedora/](https://mirrors.cloud.tencent.com/fedora/)
  - HUAWEI
    - [https://repo.huaweicloud.com/fedora/](https://repo.huaweicloud.com/fedora/)
  - 163
    - [http://mirrors.163.com/fedora/](http://mirrors.163.com/fedora/)
  - Souhu
    - [http://mirrors.sohu.com/fedora/](http://mirrors.sohu.com/fedora/)
  - 清华
    - [https://mirrors.tuna.tsinghua.edu.cn/fedora/](https://mirrors.tuna.tsinghua.edu.cn/fedora/)
  - 中科大
    - [https://mirrors.ustc.edu.cn/fedora/](https://mirrors.ustc.edu.cn/fedora/)
  - 浙江大学
    - [http://mirrors.zju.edu.cn/fedora/](http://mirrors.zju.edu.cn/fedora/)
  - 兰州大学
    - [https://mirror.lzu.edu.cn/fedora/](https://mirror.lzu.edu.cn/fedora/)
  - 上海交通
    - [http://ftp.sjtu.edu.cn/fedora/](http://ftp.sjtu.edu.cn/fedora/)
  - 南京邮电
    - [http://mirrors.njupt.edu.cn/fedora/](http://mirrors.njupt.edu.cn/fedora/)
  - 南阳理工
    - [https://mirror.nyist.edu.cn/fedora/](https://mirror.nyist.edu.cn/fedora/)
  - 重庆大学
    - [https://mirrors.cqu.edu.cn/fedora/](https://mirrors.cqu.edu.cn/fedora/)
  - 北京外国语大学
    - [https://mirrors.bfsu.edu.cn/fedora/](https://mirrors.bfsu.edu.cn/fedora/)
