title: Gentoo
content: |
  #### Official

  - 官方镜像：[https://www.gentoo.org/downloads/](https://www.gentoo.org/downloads/)

  #### Mirrors

  - [Aliyun](https://developer.aliyun.com/mirror/gentoo)
    - [https://mirrors.aliyun.com/gentoo/](https://mirrors.aliyun.com/gentoo/)
  - Tencent
    - [https://mirrors.cloud.tencent.com/gentoo/](https://mirrors.cloud.tencent.com/gentoo/)
  - HUAWEI
    - [https://repo.huaweicloud.com/gentoo/](https://repo.huaweicloud.com/gentoo/)
  - 163
    - [http://mirrors.163.com/gentoo/](http://mirrors.163.com/gentoo/)
  - Souhu
    - [http://mirrors.sohu.com/gentoo/](http://mirrors.sohu.com/gentoo/)
  - 清华
    - [https://mirrors.tuna.tsinghua.edu.cn/gentoo/](https://mirrors.tuna.tsinghua.edu.cn/gentoo/)
  - 中科大
    - [https://mirrors.ustc.edu.cn/gentoo/](https://mirrors.ustc.edu.cn/gentoo/)
  - 浙江大学
    - [http://mirrors.zju.edu.cn/gentoo/](http://mirrors.zju.edu.cn/gentoo/)
  - 兰州大学
    - [https://mirror.lzu.edu.cn/gentoo/](https://mirror.lzu.edu.cn/gentoo/)
  - 北京外国语大学
    - [https://mirrors.bfsu.edu.cn/gentoo/](https://mirrors.bfsu.edu.cn/gentoo/)
  - 上海交通
    - [https://mirrors.sjtug.sjtu.edu.cn/gentoo/](https://mirrors.sjtug.sjtu.edu.cn/gentoo/)