title: Kali
content: |
  #### Official

  - [https://www.kali.org/get-kali/](https://www.kali.org/get-kali/)

  #### Mirrors

  - [Aliyun](https://developer.aliyun.com/mirror/kali)
    - [https://mirrors.aliyun.com/kali/](https://mirrors.aliyun.com/kali/)
  - Tencent
    - [https://mirrors.cloud.tencent.com/kali/](https://mirrors.cloud.tencent.com/kali/)
  - HUAWEI
    - [https://repo.huaweicloud.com/kali/](https://repo.huaweicloud.com/kali/)
  - 清华
    - [https://mirrors.tuna.tsinghua.edu.cn/kali/](https://mirrors.tuna.tsinghua.edu.cn/kali/)
  - 中科大
    - [https://mirrors.ustc.edu.cn/kali/](https://mirrors.ustc.edu.cn/kali/)
  - 浙江大学
    - [http://mirrors.zju.edu.cn/kali/](http://mirrors.zju.edu.cn/kali/)
  - 南阳理工
    - [https://mirror.nyist.edu.cn/kali/](https://mirror.nyist.edu.cn/kali/)
  - 大连东软
    - [http://mirrors.neusoft.edu.cn/kali/](http://mirrors.neusoft.edu.cn/kali/)
  - 北京交通
    - [https://mirror.bjtu.edu.cn/kali/](https://mirror.bjtu.edu.cn/kali/)
  - 南京邮电
    - [http://mirrors.njupt.edu.cn/kali/](http://mirrors.njupt.edu.cn/kali/)
  - 西北农林科技大学
    - [https://mirrors.nwsuaf.edu.cn/kali/](https://mirrors.nwsuaf.edu.cn/kali/)
  - 重庆大学
    - [https://mirrors.cqu.edu.cn/kali-images/](https://mirrors.cqu.edu.cn/kali-images/)
  - 北京外国语大学
    - [https://mirrors.bfsu.edu.cn/kali/](https://mirrors.bfsu.edu.cn/kali/)
  - 哈尔滨工业大学
    - [https://mirrors.hit.edu.cn/kali](https://mirrors.hit.edu.cn/kali)
  - 上海交通大学
    - [https://mirrors.sjtug.sjtu.edu.cn/kali/](https://mirrors.sjtug.sjtu.edu.cn/kali/)
