title: Opensuse
content: |
  #### Official

  - [https://get.opensuse.org/zh-CN/](https://get.opensuse.org/zh-CN/)

  #### Mirrors

  - [Aliyun](https://developer.aliyun.com/mirror/opensuse)
    - [https://mirrors.aliyun.com/opensuse/](https://mirrors.aliyun.com/opensuse/)
  - Tencent
    - [https://mirrors.cloud.tencent.com/opensuse/](https://mirrors.cloud.tencent.com/opensuse/)
  - HUAWEI
    - [https://repo.huaweicloud.com/opensuse/](https://repo.huaweicloud.com/opensuse/)
  - Souhu
    - [http://mirrors.sohu.com/opensuse/](http://mirrors.sohu.com/opensuse/)
  - 北大
    - [https://mirrors.pku.edu.cn/opensuse/](https://mirrors.pku.edu.cn/opensuse/)
  - openTUNA
    - [https://opentuna.cn/opensuse/](https://opentuna.cn/opensuse/)
  - 中科大
    - [https://mirrors.ustc.edu.cn/opensuse/](https://mirrors.ustc.edu.cn/opensuse/)
  - 浙江大学
    - [http://mirrors.zju.edu.cn/opensuse/](http://mirrors.zju.edu.cn/opensuse/)
  - 兰州大学
    - [https://mirror.lzu.edu.cn/opensuse/](https://mirror.lzu.edu.cn/opensuse/)
  - 上海交通
    - [http://ftp.sjtu.edu.cn/opensuse/](http://ftp.sjtu.edu.cn/opensuse/)
  - 北京交通
    - [https://mirror.bjtu.edu.cn/opensuse/](https://mirror.bjtu.edu.cn/opensuse/)
  - 首都在线
    - [http://mirrors.yun-idc.com/opensuse/](http://mirrors.yun-idc.com/opensuse/)
  - 重庆大学
    - [https://mirrors.cqu.edu.cn/opensuse/](https://mirrors.cqu.edu.cn/opensuse/)
  - 北京理工
    - [https://mirror.bit.edu.cn/opensuse/](https://mirror.bit.edu.cn/opensuse/)
  - 重庆大学
    - [https://mirrors.cqu.edu.cn/opensuse/](https://mirrors.cqu.edu.cn/opensuse/)
  - 哈工大
    - [https://mirrors.hit.edu.cn/opensuse/](https://mirrors.hit.edu.cn/opensuse/)
  - 南京大学
    - [http://mirrors.nju.edu.cn/opensuse/](http://mirrors.nju.edu.cn/opensuse/)
  - 南方科技大学
    - [https://mirrors.sustech.edu.cn/opensuse/](https://mirrors.sustech.edu.cn/opensuse/)
  - 北京外国语大学
    - [https://mirrors.bfsu.edu.cn/opensuse/](https://mirrors.bfsu.edu.cn/opensuse/)
  - 哈尔滨工业大学
    - [https://mirrors.hit.edu.cn/opensuse/](https://mirrors.hit.edu.cn/opensuse/)
