title: Freebsd
content: |
  #### Official

  - [https://www.freebsd.org/where/](https://www.freebsd.org/where/)

  #### Mirrors

  - [Aliyun](https://developer.aliyun.com/mirror/freebsd)
    - [https://mirrors.aliyun.com/freebsd/](https://mirrors.aliyun.com/freebsd/)
  - Tencent
    - [https://mirrors.cloud.tencent.com/freebsd/](https://mirrors.cloud.tencent.com/freebsd/)
  - HUAWEI
    - [https://repo.huaweicloud.com/freebsd/](https://repo.huaweicloud.com/freebsd/)
  - 中科大
    - [https://mirrors.ustc.edu.cn/freebsd/](https://mirrors.ustc.edu.cn/freebsd/)
  - 兰州大学
    - [https://mirror.lzu.edu.cn/freebsd/](https://mirror.lzu.edu.cn/freebsd/)
  - 北京交通
    - [https://mirror.bjtu.edu.cn/freebsd/](https://mirror.bjtu.edu.cn/freebsd/)
  - 首都在线
    - [http://mirrors.yun-idc.com/freebsd/](http://mirrors.yun-idc.com/freebsd/)