name: 压缩图片
on:
  push:
    branches:
      - main
    paths:
      - 'examples/**'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}
          compressOnly: true
          jpegQuality: '60'
          jpegProgressive: false
          pngQuality: '60'
          webpQuality: '60'
      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v3
        with:
          title: Compressed Images
          branch-suffix: timestamp
          commit-message: Compressed Images
          body: ${{ steps.calibre.outputs.markdown }}