name: build

on:
  release:
    types: [created] # 表示在创建新的 Release 时触发

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          env
          echo "本次release1的版本为：${GITHUB_REF_NAME}"
          echo "本次release2的版本为：${RELEASE_TAG}"